final List<String> partyChallenges = [
  "Tómate un chupito doble",
  "Baila encima de una silla durante 1 minuto",
  "Dale un abrazo fuerte a alguien del grupo",
  "Bebe del vaso de otra persona (con su permiso)",
  "Ponte a cantar a todo pulmón la primera canción que te venga a la cabeza",
  "Quítate una prenda de ropa (si estás cómodo)",
  "Dale un beso en la mejilla a alguien",
  "Haz un brindis improvisado como si fueras el anfitrión",
  "Bebe 3 sorbos seguidos de tu copa",
  "Imita a alguien del grupo hasta que adivinen quién es",
  "Haz un striptease de 30 segundos (divertido, no serio)",
  "Cambia una prenda con otra persona",
  "Llama a alguien de tu agenda y dile 'te quiero mucho'",
  "Haz una declaración de amor ficticia a alguien del grupo",
  "Bebe con las manos atadas detrás de la espalda",
  "Deja que alguien te escriba algo en la cara con rotulador",
  "Tómate un chupito sin usar las manos",
  "Haz un baile sexy en el centro del grupo",
  "Cuenta un secreto vergonzoso",
  "Haz que todos elijan una bebida y mézclalas en un vaso (y bébelo)",
  "Dale un masaje de 1 minuto a alguien",
  "Elige a alguien y mirad fijamente a los ojos durante 30 segundos sin reírte",
  "Haz un brindis épico inventando una frase filosófica",
  "Ponte los zapatos de alguien durante 10 minutos",
  "Deja que alguien te peine como quiera",
  "Haz 5 vueltas corriendo alrededor del grupo",
  "Dale un apodo ridículo a alguien y llámalo así el resto de la noche",
  "Saca una foto graciosa y súbela a redes (si te atreves)",
  "Haz un reto de baile tipo TikTok",
  "Haz 5 flexiones mientras alguien te echa bebida en la boca",
  "Haz una confesión incómoda",
  "Ponte una prenda al revés durante toda la noche",
  "Deja que alguien elija tu próxima bebida",
  "Llama a un contacto random y ponlo en altavoz",
  "Dale un beso en la mano a alguien",
  "Haz un 'shotski' improvisado (varios beben a la vez)",
  "Bebe un vaso de agua de un tirón",
  "Haz un reto de 'verdad o shot': responde o bebe",
  "Canta con voz de ópera tu pedido de bebida",
  "Elige a dos personas y que te inventen un reto en conjunto",
  "Déjate sacar una foto vergonzosa que quedará como recuerdo de la noche",
];
